SRC_CPPS = \
           displaythread.cpp \
           main.cpp \
           pvdualsourcesample.cpp \
           source.cpp \
           sourcewidget.cpp \

EXEC     = PvDualSourceSample

include ../sample.Makefile
