SRC_CPPS = \
           aboutbox.cpp \
           actioncommanddlg.cpp \
           bufferoptionsdlg.cpp \
           connectionthread.cpp \
           displayoptionsdlg.cpp \
           displaythread.cpp \
           errorsdlg.cpp \
           eventmonitordlg.cpp \
           filteringdlg.cpp \
           gevplayer.cpp \
           imagesavedlg.cpp \
           loadingthread.cpp \
           logbuffer.cpp \
           main.cpp \
           parameterinfo.cpp \
           progressdlg.cpp \
           savingthread.cpp \
           setupdlg.cpp \
           splashscreen.cpp \
           warningdlg.cpp \

EXEC     = GEVPlayerSample

include ../sample.Makefile
